version: '1'
services:
  app:
    container_name: "message_board"
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

